name: Extension CI

on:
  push:
    branches: [ main, release-candidate/* ]
  pull_request:
    branches: [ main, release-candidate/* ]

jobs:
  build:
    strategy:
      matrix:
        os: [ macos-latest, ubuntu-latest, windows-latest ]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14'
    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: '**/node_modules'
        key: yarn-${{ hashFiles('yarn.lock') }}
        restore-keys: yarn-
      if: runner.os != 'Linux'
    - name: Install dependencies
      run: yarn install
    - name: Run tests (Linux)
      run: xvfb-run -a yarn test
      if: runner.os == 'Linux'
    - name: Run tests (non-Linux)
      run: yarn test
      if: runner.os != 'Linux'
